Header header

float32     batteryVoltage
string      flightMode
bool        serialInterfaceEnabled
bool        serialInterfaceActive
float32     flightTime
float32     cpuLoad

string      motorStatus

string      gpsStatus
int32       gpsNumberOfSatellites 

int16       status
int16       status2

bool        haveOnboardControllerParameters

uint32      txPackets
uint32      txPacketsGood
uint32      rxPackets
uint32      rxPacketsGood